#!/bin/sh -e

# replace password with your own
# cleos wallet unlock --password PW5JiugLyrkDNvgcmyVqPiw79JzX8KrXDWf9H6Z8A67MtUpmh47g2

# Deploy bios contract
# cleos set contract eosio /Users/al/Projects/eos/eos-dawn-3.0/build/contracts/eosio.bios

# Create some users
cleos create account eosio example EOS6dcmgAB4zp8KMwHau2pNFdTt4uYT9mpjgmLwuJUFrxzRcxqo83 EOS6dcmgAB4zp8KMwHau2pNFdTt4uYT9mpjgmLwuJUFrxzRcxqo83

cleos create account eosio angelo EOS6dcmgAB4zp8KMwHau2pNFdTt4uYT9mpjgmLwuJUFrxzRcxqo83 EOS6dcmgAB4zp8KMwHau2pNFdTt4uYT9mpjgmLwuJUFrxzRcxqo83


cleos create account eosio peter EOS6dcmgAB4zp8KMwHau2pNFdTt4uYT9mpjgmLwuJUFrxzRcxqo83 EOS6dcmgAB4zp8KMwHau2pNFdTt4uYT9mpjgmLwuJUFrxzRcxqo83

