#!/bin/sh -e

# replace password with your own
# cleos wallet unlock --password PW5JiugLyrkDNvgcmyVqPiw79JzX8KrXDWf9H6Z8A67MtUpmh47g2

# Deploy bios contract
# cleos set contract eosio /Users/al/Projects/eos/eos-dawn-3.0/build/contracts/eosio.bios

# Create some users
cleos create account eosio example EOS6cZ4nSPyFtfL4TyFYtsa7igiNc2JU65HmgL94WMWfX4tdcYJLH EOS6cZ4nSPyFtfL4TyFYtsa7igiNc2JU65HmgL94WMWfX4tdcYJLH

cleos create account eosio angelo EOS6cZ4nSPyFtfL4TyFYtsa7igiNc2JU65HmgL94WMWfX4tdcYJLH EOS6cZ4nSPyFtfL4TyFYtsa7igiNc2JU65HmgL94WMWfX4tdcYJLH


cleos create account eosio peter EOS6cZ4nSPyFtfL4TyFYtsa7igiNc2JU65HmgL94WMWfX4tdcYJLH EOS6cZ4nSPyFtfL4TyFYtsa7igiNc2JU65HmgL94WMWfX4tdcYJLH

